version: "3.7"

services:
  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./src:/go/src/app
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - database
      - kvs

  database:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    restart: always
  
  kvs:
    image: redis:6.0.1-alpine
    volumes:
      - kvs:/data
    ports:
      - 6379:6379
    restart: always

volumes:
  database:
  kvs:
